set nocompatible

set background=dark

" Plugins {

    source ~/.vim/plugins.vim

" }


" System {

    autocmd bufwritepost $MYVIMRC source $MYVIMRC

    filetype on
    filetype plugin on
    filetype indent on
    scriptencoding utf-8

    set history=1000
    set tags=./tags;/,~/.vimtags

" }


" Searching {

    set incsearch
    set hlsearch 
    set ignorecase
    set smartcase
    nnoremap <c-c> :noh<cr><c-c>

" }


" Editing {

    set tabstop=2
    set shiftwidth=2
    set expandtab
    set backspace=indent,eol,start
    set foldmethod=syntax
    set nofoldenable
    set undolevels=1000
    set pastetoggle=<F2>

    set wildmenu                    " show list instead of just completing
    set wildmode=list:longest,full  " command <Tab> completion, list matches, then longest common part, then all.

    set list
    set listchars=tab:,.,trail:.,extends:#,nbsp:. " Highlight problematic whitespace

" }


" Buffers {

    no <C-h> <C-w>h
    no <C-j> <C-w>j
    no <C-k> <C-w>k
    no <C-l> <C-w>l

    set hidden

" }


" Styling {

    syntax enable
    colorscheme molokai

    set showcmd
    set showmode
    set number

    set laststatus=2 " always show the status line

" }

" Plugin Settings {

  let g:airline_theme='molokai'

  map <leader>f :NERDTreeToggle<cr>
  let NERDTreeIgnore=['\.pyc', '\.beam', '\.o', '\~$', '\.swo$', '\.swp$', '\.git', '\.hg', '\.svn', '\.bzr']

  let g:ctrlp_custom_ignore = { 
      \ 'dir':  'obj$\|build$\|ebin$\|\.git$\|\.hg$\|\.svn$\|deps\|node_modules', 
      \ 'file': '\.beam$\|\.exe$\|\.so$\|\.dll$\|\.o$' }

  let g:airline_powerline_fonts = 1

" }
